#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,os,pathlib,subprocess,sys

ROOT=pathlib.Path('audit/pass2/p2c-isolated-proof-rerun-008');DEPS=pathlib.Path('audit/pass2/p2c-isolated-proof-rerun-006')
TARGET_PR_HEAD='a0d24ec35bd366b5856d84186447eae55290e0a4';TARGET_MAIN='98b2e293717b81289e3b372d1fff8f5832d29fd6';AUTH_ANCESTOR='eb83fef9c982d9f5658ebbadd402d0d9931da4b8';ORIGINAL_BLOB='cff2fffc59680e667abb53b0c18f508f6561e9eb'
OLD_CONTROLLER='repair_runner_009_controller002.py';NEW_CONTROLLER='repair_runner_009_controller002_policycompat_022.py'
OLD_PATCHER='efe861570ea5d8e63e197d468bee287ca179f849938973b1ed977658fb75af57';NEW_PATCHER='d4dd82c4787cb0464e6d7be1edff11174e0f05d7bd177a096300661f7fde2024'
OLD_MANIFEST='72d664d3ddf1890da802a5b7e00138a487682fde9859ef1c036f05c69e840619';NEW_MANIFEST='d53dc787298e8fec5f00227b680645dffd25774913ba34461d4969df6bf2b803'
OLD_CONTROLLER_SHA='ad10e91f9f8319747d08f6f882031eae48aee7c9d7813b1a3f63ad5d0e4a72f7';NEW_CONTROLLER_SHA='1a553e229078239f0d17e25ca813788b4b25aa1d33fd511cdc179f1a6ebecb13'
OLD_ALLOWLIST="allowed={'.github/workflows/pass2-p2c-isolated-proof-rerun-006.yml','audit/a002-live-runtime.cjs'}";NEW_ALLOWLIST="allowed={'.github/workflows/pass2-p2c-isolated-proof-rerun-006.yml','.github/workflows/pass2-p2c-exhaustive-preproof-discovery.yml','audit/a002-live-runtime.cjs'}"
def run(*args,check=True,env=None):return subprocess.run(list(args),text=True,capture_output=True,check=check,env=env)
def git(*args,check=True):return run('git',*args,check=check)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def blob(p):return git('hash-object',str(p)).stdout.strip()
def main():
 out=pathlib.Path(sys.argv[1]);q=[];checks=[]
 def ck(label,expected,actual,ok,order,where,repair):
  row={'label':label,'expected':expected,'actual':actual,'pass':bool(ok),'affected_file_or_binding':where};checks.append(row)
  if not ok:q.append({'dependency_order':order,**row,'consolidated_repair':repair})
 receipt_path=ROOT/'P2C_FINAL_ONE_RUN_PROOF_AUTHORIZATION_RECEIPT_026.json';repair_path=ROOT/'P2C_RECEIPT024_WRAPPER_STATIC_REPAIR_RECEIPT_025.json';reseal_path=ROOT/'P2C_EXHAUSTIVE_PREPROOF_STATIC_RESEAL_RECEIPT_023.json';wrapper=ROOT/'rerun008-controller-main-receipt024.sh';finalizer=ROOT/'rerun008-controller-finalize.sh';policy=DEPS/NEW_CONTROLLER;manifest=DEPS/'repair009-normalized-source-manifest-002.json';patcher=DEPS/'repair-continuation-003/apply_prepare_repair_003.py';candidate=ROOT/'pass2-p2c-receipt026-entry-closed.workflow-candidate.yml.txt'
 receipt=json.loads(receipt_path.read_text());repair=json.loads(repair_path.read_text());reseal=json.loads(reseal_path.read_text());checkout=git('rev-parse','HEAD').stdout.strip();gh=os.environ.get('HEAD_SHA');pr=os.environ.get('PR_HEAD_SHA');base=os.environ.get('BASE_SHA')
 ck('EVENT_ACTION_OPENED','opened',os.environ.get('EVENT_ACTION'),os.environ.get('EVENT_ACTION')=='opened',1,'workflow event','retain opened gate');ck('RUN_ATTEMPT_ONE','1',os.environ.get('RUN_ATTEMPT'),os.environ.get('RUN_ATTEMPT')=='1',2,'workflow attempt','retain first attempt');ck('CHECKOUT_EQUALS_GITHUB_SHA',checkout,gh,checkout==gh,3,'checkout identity','bind checkout to github.sha');ck('MERGE_SHA_DISTINCT_FROM_PR_HEAD',True,gh!=pr,gh!=pr,4,'workflow identity','do not chain merge SHA equality to PR head')
 exists=git('cat-file','-e',TARGET_PR_HEAD+'^{commit}',check=False).returncode==0;ck('PR90_HEAD_EXISTS',True,exists,exists,5,'PR #90 head','fetch exact head');anc=git('merge-base','--is-ancestor',TARGET_PR_HEAD,checkout,check=False).returncode==0;ck('PR90_HEAD_ANCESTOR_OF_CHECKOUT',True,anc,anc,6,'PR-head relation','bind ancestry');ck('CURRENT_MAIN',TARGET_MAIN,base,base==TARGET_MAIN,7,'main binding','bind main');auth=git('merge-base','--is-ancestor',AUTH_ANCESTOR,TARGET_PR_HEAD,check=False).returncode==0;ck('AUTH_ANCESTOR',True,auth,auth,8,'authorization ancestry','preserve ancestry')
 for n,(label,p,expected) in enumerate([('RECEIPT026_BLOB',receipt_path,'5042d0e1886ef02d02750fc4900c3a7f16ab67d9'),('RECEIPT025_BLOB',repair_path,'014900ec0a9618e1f130e5ecc3ff0a9b568142e1'),('RECEIPT023_BLOB',reseal_path,'ffdfd2e8a991c22bb95d68b57205486ec2734ead'),('WRAPPER_BLOB',wrapper,'19e708e7b0035281645914caaecc7be2dc772593'),('FINALIZER_BLOB',finalizer,'87e86c533d5d630121ded31334c46457ef4a7ad6'),('POLICY_BLOB',policy,'3818d7ae0ea3bf2de98a23e334515ca0fd6da052')],20):
  actual=blob(p);ck(label,expected,actual,actual==expected,n,str(p),'rebind authoritative file')
 for n,(label,p,expected) in enumerate([('WRAPPER_SHA',wrapper,'9daf3af5786e584488f0024c0574c843b809e95483f507ca37b3f9ec2398af96'),('FINALIZER_SHA',finalizer,'5b092ffc4c8b37b0ed6a1d32c67445aec96ae4af149630f32446700e5a86d1d4'),('PATCHER_SHA',patcher,NEW_PATCHER),('MANIFEST_SHA',manifest,NEW_MANIFEST),('POLICY_SHA',policy,NEW_CONTROLLER_SHA)],40):
  actual=sha(p);ck(label,expected,actual,actual==expected,n,str(p),'rebind exact SHA')
 ok=receipt.get('authorized') is True and receipt.get('status')=='AUTHORIZED_UNCONSUMED' and receipt.get('authorization_consumed') is False;ck('AUTH_UNCONSUMED',True,ok,ok,60,str(receipt_path),'preserve receipt truth');ck('AUTH_COUNTS',{'authorized':1,'executed':0},{'authorized':receipt.get('proof_run_count_authorized'),'executed':receipt.get('proof_run_count_executed_under_this_receipt')},receipt.get('proof_run_count_authorized')==1 and receipt.get('proof_run_count_executed_under_this_receipt')==0,61,str(receipt_path),'preserve counts')
 for i,key in enumerate(('production_application_authorized','production_activation_authorized','current_map_change_authorized','persisted_data_change_authorized','merge_authorized','second_proof_run_authorized'),62):ck('PROHIBITION_'+key.upper(),False,receipt.get(key),receipt.get(key) is False,i,str(receipt_path),'retain false')
 ck('RECEIPT025_HISTORICAL_PASS',True,repair.get('status')=='PASS_STATIC_PREFLIGHT',repair.get('status')=='PASS_STATIC_PREFLIGHT',70,str(repair_path),'preserve historical truth');ck('RECEIPT023_PASS',True,reseal.get('status')=='PASS_STATIC_RESEALED' and reseal.get('repair_queue_count')==0 and reseal.get('compile_checks_passed')==5,reseal.get('status')=='PASS_STATIC_RESEALED' and reseal.get('repair_queue_count')==0 and reseal.get('compile_checks_passed')==5,71,str(reseal_path),'preserve reseal')
 changed=set(git('diff','--name-only',TARGET_MAIN,TARGET_PR_HEAD).stdout.splitlines());allowed={'.github/workflows/pass2-p2c-isolated-proof-rerun-006.yml','.github/workflows/pass2-p2c-exhaustive-preproof-discovery.yml','audit/a002-live-runtime.cjs'};extras=sorted(p for p in changed if p not in allowed and not p.startswith('audit/pass2/p2c-isolated-proof-rerun-006/') and not p.startswith('audit/pass2/p2c-isolated-proof-rerun-008/'));ck('CHANGED_PATH_ALLOWLIST',[],extras,not extras,80,'allowlist','include exhaustive workflow');cache=sorted(p for p in changed if '/__pycache__/' in p or p.endswith('.pyc'));ck('CACHE_EXCLUSION',[],cache,not cache,81,'cache','remove cache')
 ctext=candidate.read_text();requirements=[("assert os.environ['HEAD_SHA']==checkout_head",True),("subprocess.run(['git','merge-base','--is-ancestor',os.environ['PR_HEAD_SHA'],checkout_head],check=True)",True),("'.github/workflows/pass2-p2c-exhaustive-preproof-discovery.yml'",True),("os.environ['HEAD_SHA']==os.environ['PR_HEAD_SHA']",False)]
 for i,(snippet,present) in enumerate(requirements,82):ck('CANDIDATE_'+str(i),present,snippet in ctext,(snippet in ctext)==present,i,str(candidate),'repair candidate')
 original=git('cat-file','blob',ORIGINAL_BLOB).stdout;before={'old_controller':original.count(OLD_CONTROLLER),'old_patcher':original.count(OLD_PATCHER),'old_manifest':original.count(OLD_MANIFEST),'old_controller_sha':original.count(OLD_CONTROLLER_SHA),'old_allowlist':original.count(OLD_ALLOWLIST)};expected={'old_controller':4,'old_patcher':1,'old_manifest':1,'old_controller_sha':1,'old_allowlist':1}
 for i,k in enumerate(expected,90):ck('BEFORE_'+k.upper(),expected[k],before[k],before[k]==expected[k],i,str(wrapper),'correct census')
 text=original.replace(OLD_PATCHER,NEW_PATCHER).replace(OLD_MANIFEST,NEW_MANIFEST).replace(OLD_CONTROLLER,NEW_CONTROLLER).replace(OLD_CONTROLLER_SHA,NEW_CONTROLLER_SHA).replace(OLD_ALLOWLIST,NEW_ALLOWLIST);materialized=pathlib.Path('/tmp/p2c-proof-entry-closure-materialized-027.sh');materialized.write_text(text);after={'old_controller':text.count(OLD_CONTROLLER),'new_controller':text.count(NEW_CONTROLLER),'new_patcher':text.count(NEW_PATCHER),'new_manifest':text.count(NEW_MANIFEST),'new_controller_sha':text.count(NEW_CONTROLLER_SHA),'old_allowlist':text.count(OLD_ALLOWLIST),'new_allowlist':text.count(NEW_ALLOWLIST)};expected2={'old_controller':0,'new_controller':4,'new_patcher':1,'new_manifest':1,'new_controller_sha':1,'old_allowlist':0,'new_allowlist':1}
 for i,k in enumerate(expected2,100):ck('AFTER_'+k.upper(),expected2[k],after[k],after[k]==expected2[k],i,str(materialized),'exact final state')
 syntax=run('bash','-n',str(materialized),check=False);ck('SHELL_SYNTAX',0,{'rc':syntax.returncode,'stderr':syntax.stderr},syntax.returncode==0,110,str(materialized),'repair syntax');marker='echo "=== Create exact detached baseline and active worktrees ==="';ck('HARD_STOP_MARKER',1,text.count(marker),text.count(marker)==1,111,str(materialized),'one boundary')
 reached=False;rc=None;stdout='';stderr=''
 if not q and text.count(marker)==1:
  diag=pathlib.Path('/tmp/p2c-proof-entry-closure-preworktree-027.sh');diag.write_text(text.split(marker,1)[0]+"\nprintf '%s\\n' 'PROOF_ENTRY_CLOSURE_HARD_STOP_BEFORE_GIT_WORKTREE_ADD'\n");env=os.environ.copy();env.update({'EVENT_ACTION':'opened','RUN_ATTEMPT':'1','HEAD_SHA':checkout,'BASE_SHA':TARGET_MAIN,'SOURCE_COMMIT':TARGET_MAIN,'AUDIT_DIR':str(ROOT),'DEPS_DIR':str(DEPS),'REPAIR_DIR':str(DEPS/'repair-continuation-003'),'BUNDLE_DIR':'/tmp/p2c-closure-bundle-027','BUNDLE_TAR':'/tmp/p2c-closure-bundle-027.tar.gz','BASELINE_ROOT':'/tmp/p2c-closure-baseline-027','ACTIVE_ROOT':'/tmp/p2c-closure-active-027','EVIDENCE_DIR':'/tmp/p2c-closure-evidence-027','NORMALIZED_ROOT':'/tmp/p2c-closure-normalized-027','NODE_HOME':'/tmp/p2c-closure-node-027','RUN_ID':'DIAGNOSTIC_ONLY_027'});p=run('bash',str(diag),check=False,env=env);rc=p.returncode;stdout=p.stdout;stderr=p.stderr;reached=rc==0 and 'PROOF_ENTRY_CLOSURE_HARD_STOP_BEFORE_GIT_WORKTREE_ADD' in stdout;ck('REACH_PREWORKTREE_STOP',True,{'rc':rc,'stdout_tail':stdout[-4000:],'stderr_tail':stderr[-4000:]},reached,120,str(diag),'repair complete preworktree set')
 q.sort(key=lambda x:(x['dependency_order'],x['label']));report={'type':'PMP_PASS2_PROOF_ENTRY_CLOSURE_027','status':'PASS_ZERO_REPAIR_QUEUE_REACHED_PRE_WORKTREE_HARD_STOP' if not q and reached else 'COMPLETE_PROOF_ENTRY_FAILURE_SET_COLLECTED','target_pr':90,'target_pr_head':TARGET_PR_HEAD,'repair_queue_count':len(q),'repair_queue_dependency_ordered':q,'checks':checks,'candidate_path':str(candidate),'preworktree_returncode':rc,'preworktree_stdout_tail':stdout[-8000:],'preworktree_stderr_tail':stderr[-8000:],'hard_stop':{'reached_immediately_before_git_worktree_add':reached,'git_worktree_add_executed':False,'playwright_or_chromium_install_executed':False,'disposable_copy_preparation_executed':False,'browser_proof_executed':False,'proof_run_count_executed':0,'proof_authorized_by_closure_pass':False,'production_files_modified':False,'current_map_modified':False,'persisted_data_modified':False}}
 out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n');print(json.dumps(report,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
