'use strict';
const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const source=fs.readFileSync('pmp-diagnostic-coverage-passes-bcd-v1.js','utf8');
new vm.Script(source,{filename:'pmp-diagnostic-coverage-passes-bcd-v1.js'});
assert(source.includes("CONTINUOUS_RUN_CANONICAL_LEVEL_RECEIPT_V1"));
assert(source.includes("mounted_validation:bankOpen?'REQUIRED_AND_EVALUATED':'DEFERRED_UNTIL_BANK_OPEN'"));
assert(source.includes('CONTINUOUS_RUN_LEVELS_NOT_MOUNTED_WHILE_BANK_OPEN'));
assert(!source.includes("if(!levels.length)issues.push({code:'CONTINUOUS_RUN_LEVELS_NOT_MOUNTED'}"));
assert(source.includes("PMPDiagnosticJournalContractV1"));
assert(source.includes("PMPDiagnosticJournalReadonlyViewExportV1"));
assert(source.includes("pmp_diagnostic_journal_v1_receipt"));
assert(source.includes("pmp_diagnostic_journal_view_v1_receipt"));
assert(source.includes("viewApi.read({limit:64})"));
assert(source.includes("journal_entries_added:0"));
assert(source.includes("owner_changes:false"));
assert(source.includes("helper_changes:false"));
assert(source.includes("route_changes:false"));
assert(source.includes("persisted_user_data_writes:false"));
assert(source.includes("dom_repair:false"));
console.log('PASS final two Whole App Health live proofs');
