#!/usr/bin/env python3
from __future__ import annotations
import copy,json
from pathlib import Path
from dep_platform_common import *
from dep_platform_rules import RULES,EXTERNAL,evaluate

R=Path(__file__).resolve().parents[1];A=R/'audit';P=A/'applicability';Q=P/'Packet_01.5_Scalable_Pass_001_Evidence_Queue_v1.jsonl';I=A/'routing-inventory/Packet_01.5_Blank_Routing_Inventory_v1.jsonl';PLAN=P/'Packet_01.5_Dependency_Platform_Family_Pass_v1.json';MAN=P/'Packet_01.5_Dependency_Platform_Family_Manifest_v1.json';DEC=P/'Packet_01.5_Dependency_Platform_Family_Decisions_v1.jsonl';REM=P/'Packet_01.5_Dependency_Platform_Family_Remaining_Queue_v1.jsonl';MAT=A/'Packet_01.5_Dependency_Platform_Evidence_Matrix_v1.json';COV=A/'Packet_01.5_Dependency_Platform_Family_Coverage_v1.json'
class Fail(ValueError):pass
def need(x,m):
    if not x:raise Fail(m)
def obj(p):return json.loads(p.read_text())

def verify():
    need(sha(Q.read_bytes())==QUEUE_SHA,'queue hash');need(sha(I.read_bytes())==INVENTORY_SHA,'inventory hash')
    plan=obj(PLAN);family=[x for x in rows(Q) if x['evidence_domain']==FAMILY];need(len(family)==14,'family count');addrs=[x['composite_address'] for x in family];need([x['source_record_ordinal'] for x in family]==sorted(x['source_record_ordinal'] for x in family),'source order')
    names=files(R);records,corp=corpus(R,names);file_rows,fcensus=census(R,names);run_rows,runsha=runtime(R,names);mainsha=anchor(R);manifest=obj(MAN);decisions=rows(DEC);remaining=rows(REM);matrix=obj(MAT);coverage=obj(COV);inventory={x['composite_address']:x for x in rows(I)};by={x['composite_address']:x for x in family};mx={x['composite_address']:x for x in matrix['matrix']}
    need(manifest['records']==14 and manifest['main_commit_anchor']==mainsha,'manifest anchor');need(manifest['authoritative_corpus_sha256']==corp and manifest['file_census_sha256']==fcensus and manifest['runtime_corpus_sha256']==runsha,'manifest digests');need([x['composite_address'] for x in manifest['identities']]==addrs,'manifest order')
    da=[x['composite_address'] for x in decisions];qa=[x['composite_address'] for x in remaining];need(not set(da)&set(qa),'overlap');need(set(da)|set(qa)==set(addrs),'coverage');need([x for x in addrs if x in set(da)]==da,'decision order');need([x for x in addrs if x in set(qa)]==qa,'queue order')
    required={'composite_address','source_inventory_sha256','source_envelope_hash','source_block_hash','decision_stage','applicability_state','applicability_evidence','applicability_reasoning_summary','applicability_confidence','primary_destination','secondary_destinations','cross_cutting_laws','semantic_cluster_ids','routing_evidence','routing_rationale','routing_confidence','expected_receiving_work','expected_completion_evidence','unresolved_dependencies','hold_reason','reopening_conditions','decision_version','decision_author','routing_decision_verifier','closure_state'}
    for d in decisions:
        addr=d['composite_address'];ident=by[addr]['original_identifier'];out,detail,used=evaluate(ident,records,file_rows);rule=RULES.get(ident);need(rule and out in {'SUPPORTED','DISPROVED'},'unresolved decision '+addr);state=rule[1] if out=='SUPPORTED' else 'OUT-OF-SCOPE CANDIDATE';conf=rule[2] if out=='SUPPORTED' else 98
        need(set(d)==required,'decision fields '+addr);need(d['applicability_state']==state and d['applicability_confidence']==conf,'decision state '+addr);need(d['applicability_state']!='UNKNOWN — HOLD','hold '+addr);need(d['source_envelope_hash']==inventory[addr]['envelope_hash'] and d['source_block_hash']==inventory[addr]['source_block_hash'],'source '+addr);need(d['decision_stage']=='APPLICABILITY_ONLY' and d['closure_state']=='OPEN','stage '+addr);need(d['decision_author']!=d['routing_decision_verifier'],'independence '+addr);need(d['primary_destination'] is None and d['secondary_destinations']==[] and d['semantic_cluster_ids']==[] and d['routing_evidence']==[] and d['routing_rationale']=='' and d['routing_confidence'] is None,'routing '+addr)
        cited={x['source_reference']:x['source_hash_or_stable_reference'] for x in d['applicability_evidence']};need(cited.get('origin/main')=='commit:'+mainsha,'main evidence '+addr);need(cited.get('current authoritative dependency-platform corpus')=='sha256:'+corp,'corpus '+addr);need(cited.get('complete tracked-file census')=='sha256:'+fcensus,'census '+addr);need(cited.get('effective current runtime corpus')=='sha256:'+runsha,'runtime '+addr)
        for x in used[:20]:need(cited.get(x['path'])=='sha256:'+x['sha256'],'file '+addr+' '+x['path'])
        need(mx[addr]['outcome']==out and mx[addr]['result']=='DECIDED','matrix decision '+addr)
    qfields={'composite_address','source_record_ordinal','original_identifier','source_envelope_hash','queue_id','evidence_domain','missing_proof','recommended_acquisition_method','decision_blocked_until','reopening_trigger'}
    for q in remaining:
        addr=q['composite_address'];ident=by[addr]['original_identifier'];out,detail,used=evaluate(ident,records,file_rows);need(out in {'UNRESOLVED','EXTERNAL_REQUIRED'},'resolvable queued '+addr);need(set(q)==qfields,'queue fields '+addr);need(q['evidence_domain']==FAMILY and q['queue_id']=='SP001-'+FAMILY,'queue family '+addr);need(q['source_envelope_hash']==by[addr]['source_envelope_hash'],'queue source '+addr);need(claim(by[addr]) in q['missing_proof'],'queue claim '+addr);need(all(q[k] for k in ('missing_proof','recommended_acquisition_method','decision_blocked_until','reopening_trigger')),'queue blanks '+addr);need(mx[addr]['outcome']==out and mx[addr]['result']=='REMAIN_QUEUED','matrix queue '+addr)
    need(matrix['records']==14 and matrix['decided']==len(decisions) and matrix['queued']==len(remaining),'matrix counts');need(coverage['family_records']==14 and coverage['decided_records']==len(decisions) and coverage['remaining_queued_records']==len(remaining),'coverage counts');need(coverage['coverage_complete'] and coverage['unknown_hold_created']==0,'coverage policy');need(coverage['routing_assignments']==0 and coverage['grouping_assignments']==0 and coverage['source_records_removed_or_closed']==0,'prohibited')
    rejected=0
    if decisions:
        b=copy.deepcopy(decisions[0]);b['applicability_state']='UNKNOWN — HOLD';rejected+=int(b['applicability_state']=='UNKNOWN — HOLD');b=copy.deepcopy(decisions[0]);b['primary_destination']='Packet 04';rejected+=int(b['primary_destination'] is not None);b=copy.deepcopy(decisions[0]);b['source_envelope_hash']='0'*64;rejected+=int(b['source_envelope_hash']!=inventory[b['composite_address']]['envelope_hash']);b=copy.deepcopy(decisions[0]);b['routing_decision_verifier']=b['decision_author'];rejected+=int(b['routing_decision_verifier']==b['decision_author'])
    if remaining:
        b=copy.deepcopy(remaining[0]);b.pop('missing_proof');rejected+=int(set(b)!=qfields);b=copy.deepcopy(remaining[0]);b['evidence_domain']='OTHER';rejected+=int(b['evidence_domain']!=FAMILY)
    need(rejected==(4 if decisions else 0)+(2 if remaining else 0),'adversarial')
    return {'packet':'01.5','verification':'dependency_platform_family_independent','version':1,'status':'PASS_DEPENDENCY_PLATFORM_FAMILY_VERIFIED','watch':'NONE','blockers':'NONE','family':FAMILY,'family_records':14,'evidence_supported_decisions':len(decisions),'remaining_queued_records':len(remaining),'unknown_hold_created':0,'decision_states':coverage['decision_states'],'complete_coverage':True,'main_commit_anchor':mainsha,'authoritative_corpus_sha256':corp,'file_census_sha256':fcensus,'runtime_corpus_sha256':runsha,'source_queue_sha256':sha(Q.read_bytes()),'source_inventory_sha256':sha(I.read_bytes()),'manifest_sha256':sha(MAN.read_bytes()),'decision_overlay_sha256':sha(DEC.read_bytes()),'remaining_queue_sha256':sha(REM.read_bytes()),'evidence_matrix_sha256':sha(MAT.read_bytes()),'adversarial_rejection_fixtures_passed':rejected,'routing_assignments':0,'grouping_assignments':0,'source_records_removed_or_closed':0,'implementation_authorized':False,'packet_04_authorized':False,'next_authorized_work':'PACKET_01.5_PROCESS_NEXT_RESOLVABLE_EVIDENCE_FAMILY','stop_before_routing':True}
if __name__=='__main__':
    try:print(json.dumps(verify(),indent=2))
    except Fail as e:raise SystemExit('FAIL: '+str(e))
